#include "contracts/contracts.h"

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>

#include <algorithm>

namespace modernime {
namespace {
QString qs(const std::string &value) { return QString::fromUtf8(value.data(), static_cast<qsizetype>(value.size())); }
std::string ss(const QString &value) { return value.toUtf8().toStdString(); }
QString layoutName(CandidateLayout value) { return value == CandidateLayout::Vertical ? QStringLiteral("vertical") : QStringLiteral("horizontal"); }
CandidateLayout parseLayout(const QString &value) { return value == QStringLiteral("vertical") ? CandidateLayout::Vertical : CandidateLayout::Horizontal; }
QString triggerName(VoiceTriggerMode value) { return value == VoiceTriggerMode::Toggle ? QStringLiteral("toggle") : QStringLiteral("push_to_talk"); }
VoiceTriggerMode parseTrigger(const QString &value) { return value == QStringLiteral("toggle") ? VoiceTriggerMode::Toggle : VoiceTriggerMode::PushToTalk; }
VoiceState parseVoiceState(const QString &value) { if (value == QStringLiteral("starting")) return VoiceState::Starting; if (value == QStringLiteral("listening")) return VoiceState::Listening; if (value == QStringLiteral("finalizing")) return VoiceState::Finalizing; if (value == QStringLiteral("review")) return VoiceState::Review; if (value == QStringLiteral("committing")) return VoiceState::Committing; if (value == QStringLiteral("error")) return VoiceState::Error; return VoiceState::Idle; }
std::optional<ErrorCode> parseErrorCode(const QString &value) { if (value == QStringLiteral("AudioDeviceMissing")) return ErrorCode::AudioDeviceMissing; if (value == QStringLiteral("AudioPermissionDenied")) return ErrorCode::AudioPermissionDenied; if (value == QStringLiteral("AudioBufferOverrun")) return ErrorCode::AudioBufferOverrun; if (value == QStringLiteral("ModelMissing")) return ErrorCode::ModelMissing; if (value == QStringLiteral("ModelCorrupt")) return ErrorCode::ModelCorrupt; if (value == QStringLiteral("ModelLoadFailed")) return ErrorCode::ModelLoadFailed; if (value == QStringLiteral("RecognizerTooSlow")) return ErrorCode::RecognizerTooSlow; if (value == QStringLiteral("FocusChanged")) return ErrorCode::FocusChanged; if (value == QStringLiteral("EmptySpeech")) return ErrorCode::EmptySpeech; if (value == QStringLiteral("StorageFailure")) return ErrorCode::StorageFailure; if (value == QStringLiteral("InvalidRequest")) return ErrorCode::InvalidRequest; return std::nullopt; }
QJsonObject objectFrom(std::string_view value) { const auto document = QJsonDocument::fromJson(QByteArray(value.data(), static_cast<qsizetype>(value.size()))); return document.isObject() ? document.object() : QJsonObject{}; }
}

std::string escapeJson(std::string_view value) { return ss(QString::fromUtf8(value.data(), static_cast<qsizetype>(value.size())).toHtmlEscaped()); }

std::string serialize(const CandidateSnapshot &snapshot) {
    QJsonObject object; object.insert(QStringLiteral("protocol_version"), static_cast<int>(snapshot.protocol_version)); object.insert(QStringLiteral("producer_id"), qs(snapshot.producer_id)); object.insert(QStringLiteral("sequence"), static_cast<qint64>(snapshot.sequence)); object.insert(QStringLiteral("preedit"), qs(snapshot.preedit)); object.insert(QStringLiteral("selected"), snapshot.selected); object.insert(QStringLiteral("page"), snapshot.page); object.insert(QStringLiteral("pages"), snapshot.pages); object.insert(QStringLiteral("layout"), layoutName(snapshot.layout)); object.insert(QStringLiteral("mode"), qs(snapshot.mode)); object.insert(QStringLiteral("cursor_x"), snapshot.cursor_x); object.insert(QStringLiteral("cursor_y"), snapshot.cursor_y); object.insert(QStringLiteral("cursor_height"), snapshot.cursor_height); object.insert(QStringLiteral("visible"), snapshot.visible);
    QJsonArray candidates; for (const auto &candidate : snapshot.candidates) { QJsonObject item; item.insert(QStringLiteral("text"), qs(candidate.text)); item.insert(QStringLiteral("annotation"), qs(candidate.annotation)); item.insert(QStringLiteral("pinned"), candidate.pinned); item.insert(QStringLiteral("literal"), candidate.literal); candidates.append(item); } object.insert(QStringLiteral("candidates"), candidates); return QJsonDocument(object).toJson(QJsonDocument::Compact).toStdString();
}
std::optional<CandidateSnapshot> parseCandidateSnapshot(std::string_view value) { const auto object = objectFrom(value); if (object.isEmpty() || object.value(QStringLiteral("protocol_version")).toInt() != static_cast<int>(kProtocolVersion)) return std::nullopt; CandidateSnapshot result; result.producer_id = ss(object.value(QStringLiteral("producer_id")).toString()); result.sequence = object.value(QStringLiteral("sequence")).toInteger(); result.preedit = ss(object.value(QStringLiteral("preedit")).toString()); result.selected = object.value(QStringLiteral("selected")).toInt(); result.page = object.value(QStringLiteral("page")).toInt(1); result.pages = object.value(QStringLiteral("pages")).toInt(1); result.layout = parseLayout(object.value(QStringLiteral("layout")).toString()); result.mode = ss(object.value(QStringLiteral("mode")).toString(QStringLiteral("中文"))); result.cursor_x = object.value(QStringLiteral("cursor_x")).toInt(-1); result.cursor_y = object.value(QStringLiteral("cursor_y")).toInt(-1); result.cursor_height = object.value(QStringLiteral("cursor_height")).toInt(); result.visible = object.value(QStringLiteral("visible")).toBool(); for (const auto value : object.value(QStringLiteral("candidates")).toArray()) { const auto candidate = value.toObject(); result.candidates.push_back({ss(candidate.value(QStringLiteral("text")).toString()), ss(candidate.value(QStringLiteral("annotation")).toString()), candidate.value(QStringLiteral("pinned")).toBool(), candidate.value(QStringLiteral("literal")).toBool()}); } return result; }

std::string serialize(const ConfigSnapshot &snapshot) { QJsonObject object; object.insert(QStringLiteral("protocol_version"), static_cast<int>(snapshot.protocol_version)); object.insert(QStringLiteral("version"), static_cast<qint64>(snapshot.version)); object.insert(QStringLiteral("chinese_mode"), snapshot.chinese_mode); object.insert(QStringLiteral("insert_spacing"), snapshot.insert_spacing); object.insert(QStringLiteral("candidate_count"), snapshot.candidate_count); object.insert(QStringLiteral("layout"), layoutName(snapshot.layout)); object.insert(QStringLiteral("font_size"), snapshot.font_size); object.insert(QStringLiteral("corner_radius"), snapshot.corner_radius); object.insert(QStringLiteral("opacity"), snapshot.opacity); object.insert(QStringLiteral("voice_trigger"), triggerName(snapshot.voice_trigger)); object.insert(QStringLiteral("voice_auto_commit"), snapshot.voice_auto_commit); object.insert(QStringLiteral("voice_hotkey"), qs(snapshot.voice_hotkey)); object.insert(QStringLiteral("cancel_hotkey"), qs(snapshot.cancel_hotkey)); object.insert(QStringLiteral("commit_raw_hotkey"), qs(snapshot.commit_raw_hotkey)); object.insert(QStringLiteral("previous_page_hotkey"), qs(snapshot.previous_page_hotkey)); object.insert(QStringLiteral("next_page_hotkey"), qs(snapshot.next_page_hotkey)); object.insert(QStringLiteral("previous_candidate_hotkey"), qs(snapshot.previous_candidate_hotkey)); object.insert(QStringLiteral("next_candidate_hotkey"), qs(snapshot.next_candidate_hotkey)); object.insert(QStringLiteral("microphone"), qs(snapshot.microphone)); object.insert(QStringLiteral("model_id"), qs(snapshot.model_id)); return QJsonDocument(object).toJson(QJsonDocument::Compact).toStdString(); }
std::optional<ConfigSnapshot> parseConfigSnapshot(std::string_view value) { const auto object = objectFrom(value); if (object.isEmpty() || object.value(QStringLiteral("protocol_version")).toInt() != static_cast<int>(kProtocolVersion)) return std::nullopt; ConfigSnapshot result; result.version = object.value(QStringLiteral("version")).toInteger(1); result.chinese_mode = object.value(QStringLiteral("chinese_mode")).toBool(true); result.insert_spacing = object.value(QStringLiteral("insert_spacing")).toBool(true); result.candidate_count = std::clamp(object.value(QStringLiteral("candidate_count")).toInt(7), 3, 9); result.layout = parseLayout(object.value(QStringLiteral("layout")).toString()); result.font_size = std::clamp(object.value(QStringLiteral("font_size")).toInt(15), 12, 32); result.corner_radius = std::clamp(object.value(QStringLiteral("corner_radius")).toInt(10), 0, 32); result.opacity = std::clamp(object.value(QStringLiteral("opacity")).toInt(96), 65, 100); result.voice_trigger = parseTrigger(object.value(QStringLiteral("voice_trigger")).toString()); result.voice_auto_commit = object.value(QStringLiteral("voice_auto_commit")).toBool(); if (object.contains(QStringLiteral("voice_hotkey"))) result.voice_hotkey = ss(object.value(QStringLiteral("voice_hotkey")).toString()); if (object.contains(QStringLiteral("cancel_hotkey"))) result.cancel_hotkey = ss(object.value(QStringLiteral("cancel_hotkey")).toString()); if (object.contains(QStringLiteral("commit_raw_hotkey"))) result.commit_raw_hotkey = ss(object.value(QStringLiteral("commit_raw_hotkey")).toString()); if (object.contains(QStringLiteral("previous_page_hotkey"))) result.previous_page_hotkey = ss(object.value(QStringLiteral("previous_page_hotkey")).toString()); if (object.contains(QStringLiteral("next_page_hotkey"))) result.next_page_hotkey = ss(object.value(QStringLiteral("next_page_hotkey")).toString()); if (object.contains(QStringLiteral("previous_candidate_hotkey"))) result.previous_candidate_hotkey = ss(object.value(QStringLiteral("previous_candidate_hotkey")).toString()); if (object.contains(QStringLiteral("next_candidate_hotkey"))) result.next_candidate_hotkey = ss(object.value(QStringLiteral("next_candidate_hotkey")).toString()); if (object.contains(QStringLiteral("microphone"))) result.microphone = ss(object.value(QStringLiteral("microphone")).toString()); if (object.contains(QStringLiteral("model_id"))) result.model_id = ss(object.value(QStringLiteral("model_id")).toString()); return result; }

std::string voiceStateName(VoiceState state) { switch (state) { case VoiceState::Starting: return "starting"; case VoiceState::Listening: return "listening"; case VoiceState::Finalizing: return "finalizing"; case VoiceState::Review: return "review"; case VoiceState::Committing: return "committing"; case VoiceState::Error: return "error"; default: return "idle"; } }
std::string errorCodeName(ErrorCode code) { switch (code) { case ErrorCode::AudioDeviceMissing: return "AudioDeviceMissing"; case ErrorCode::AudioPermissionDenied: return "AudioPermissionDenied"; case ErrorCode::AudioBufferOverrun: return "AudioBufferOverrun"; case ErrorCode::ModelMissing: return "ModelMissing"; case ErrorCode::ModelCorrupt: return "ModelCorrupt"; case ErrorCode::ModelLoadFailed: return "ModelLoadFailed"; case ErrorCode::RecognizerTooSlow: return "RecognizerTooSlow"; case ErrorCode::FocusChanged: return "FocusChanged"; case ErrorCode::EmptySpeech: return "EmptySpeech"; case ErrorCode::StorageFailure: return "StorageFailure"; default: return "InvalidRequest"; } }
std::string serialize(const VoiceEvent &event) { QJsonObject object; object.insert(QStringLiteral("protocol_version"), static_cast<int>(event.protocol_version)); object.insert(QStringLiteral("session_id"), qs(event.session_id)); object.insert(QStringLiteral("focus_generation"), static_cast<qint64>(event.focus_generation)); object.insert(QStringLiteral("state"), qs(voiceStateName(event.state))); object.insert(QStringLiteral("text"), qs(event.text)); object.insert(QStringLiteral("level"), event.level); object.insert(QStringLiteral("stability"), event.stability); if (event.error) object.insert(QStringLiteral("error"), qs(errorCodeName(*event.error))); return QJsonDocument(object).toJson(QJsonDocument::Compact).toStdString(); }
std::optional<VoiceEvent> parseVoiceEvent(std::string_view value) { const auto object = objectFrom(value); if (object.isEmpty() || object.value(QStringLiteral("protocol_version")).toInt() != static_cast<int>(kProtocolVersion)) return std::nullopt; VoiceEvent result; result.session_id = ss(object.value(QStringLiteral("session_id")).toString()); result.focus_generation = object.value(QStringLiteral("focus_generation")).toInteger(); result.state = parseVoiceState(object.value(QStringLiteral("state")).toString()); result.text = ss(object.value(QStringLiteral("text")).toString()); result.level = static_cast<float>(object.value(QStringLiteral("level")).toDouble()); result.stability = static_cast<float>(object.value(QStringLiteral("stability")).toDouble()); result.error = parseErrorCode(object.value(QStringLiteral("error")).toString()); return result; }
} // namespace modernime
