#include "contracts/contracts.h"
#include <catch2/catch_test_macros.hpp>
TEST_CASE("candidate snapshot serialization is versioned and round trips") { modernime::CandidateSnapshot input; input.producer_id = "engine-instance-a"; input.sequence = 42; input.preedit = "nihao"; input.candidates = {{"你好", "拼音", false, false}, {"nihao", "原文", false, true}}; input.visible = true; const auto parsed = modernime::parseCandidateSnapshot(modernime::serialize(input)); REQUIRE(parsed); REQUIRE(parsed->producer_id == "engine-instance-a"); REQUIRE(parsed->sequence == 42); REQUIRE(parsed->candidates.at(0).text == "你好"); REQUIRE(parsed->visible); }
TEST_CASE("config validation clamps unsafe visual values") { auto parsed = modernime::parseConfigSnapshot("{\"protocol_version\":1,\"candidate_count\":99,\"font_size\":1,\"corner_radius\":90,\"opacity\":1}"); REQUIRE(parsed); REQUIRE(parsed->candidate_count == 9); REQUIRE(parsed->font_size == 12); REQUIRE(parsed->corner_radius == 32); REQUIRE(parsed->opacity == 65); }
TEST_CASE("config migrations require explicit microphone selection and retain the model default") { auto parsed = modernime::parseConfigSnapshot("{\"protocol_version\":1}"); REQUIRE(parsed); REQUIRE(parsed->microphone.empty()); REQUIRE(parsed->model_id == "sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20"); }
TEST_CASE("candidate themes round trip and unknown themes retain the current default") { modernime::ConfigSnapshot input; input.theme = modernime::CandidateTheme::Starlight; const auto saved = modernime::parseConfigSnapshot(modernime::serialize(input)); REQUIRE(saved); REQUIRE(saved->theme == modernime::CandidateTheme::Starlight); const auto unknown = modernime::parseConfigSnapshot("{\"protocol_version\":1,\"theme\":\"not-a-theme\"}"); REQUIRE(unknown); REQUIRE(unknown->theme == modernime::CandidateTheme::Midnight); }
TEST_CASE("hotkey configuration round trips with portable Fcitx names") { modernime::ConfigSnapshot input; input.voice_hotkey = "Control+F8"; input.cancel_hotkey = "Control+Escape"; input.next_page_hotkey = "bracketright"; const auto parsed = modernime::parseConfigSnapshot(modernime::serialize(input)); REQUIRE(parsed); REQUIRE(parsed->voice_hotkey == "Control+F8"); REQUIRE(parsed->cancel_hotkey == "Control+Escape"); REQUIRE(parsed->next_page_hotkey == "bracketright"); }
TEST_CASE("voice error round trips with a stable error code") { modernime::VoiceEvent input; input.session_id = "voice-1"; input.state = modernime::VoiceState::Error; input.error = modernime::ErrorCode::ModelMissing; const auto parsed = modernime::parseVoiceEvent(modernime::serialize(input)); REQUIRE(parsed); REQUIRE(parsed->error == modernime::ErrorCode::ModelMissing); }
TEST_CASE("unknown protocol is rejected") { REQUIRE_FALSE(modernime::parseVoiceEvent("{\"protocol_version\":7}")); }
